spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# ========== RABBITMQ ==========
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ========== APP CONFIG ==========
app.rabbitmq.exchange=order.exchange
app.rabbitmq.routing-key.order-created=order.created
app.rabbitmq.routing-key.payment-result=payment.result
app.rabbitmq.queue.payment-result=ecommerce.payment.result.queue